### ISSUE TITLE
Lacking support for `SVCB` RR in the QType matcher

### ISSUE THREAD

**Issue by fox85** [LEXUGE/dcompass#13]
尝试在配置文件添加过滤qtype，希望能把qtype64 , qtype65 即 SVCB和HTTPS类型的请求过滤，不过就报错了

Caused by:
    table[0].if.qtype[1]: unknown variant `SVCB`

Caused by:
    table[0].if.qtype[1]: unknown variant `64`, 

希望大佬能尽快支持对特定的qtype值过滤，谢谢！

**Comment by LEXUGE** [comment]
看了一下, `SVCB` 是似乎还在草案的 RR， https://tools.ietf.org/id/draft-nygren-dnsop-svcb-httpssvc-00.html

目前 qtype 是按照 trust-dns lib 里的库支持的 Record Type 实现的，参见 https://docs.rs/trust-dns-proto/0.20.0/trust_dns_proto/rr/record_type/enum.RecordType.html

鉴于目前是草案，我可以像上游提出支持，不过不知道实现情况会怎样。

**Comment by LEXUGE** [comment]
不过好奇过滤 SVCB 是什么场景呢？

**Comment by fox85** [comment]
SVCB暂时我也未了解应用在什么场景，不过能预先支持还是好的，因为它跟HTTPS是一对的（不知道这个比喻不对）  😸

**Comment by LEXUGE** [comment]
会去跟进，但是 SVBC 看起来是会降级的，对其过滤也没有什么意义（而且大多数 Record 都没有这个记录，因为这不是标准）

**Comment by fox85** [comment]
感谢大佬的快速回复。
HTTPS的过滤希望可以尽快增加实现，因为目前IOS系统发出的请求会包含这个，但这样就破坏了翻墙CDN加速的效果了

**Comment by LEXUGE** [comment]
```
  if:
    qtype:
      - Unknown: 65
      - Unknown: 64
```

可以这么写

**Comment by bcookatpcsd** [comment]
Sorry for the necrobump.. I recently found this project, looking for a rust resolver - thank you.. 

Is there a way to block all qtypes, and then whitelist what you would want to work, instead of blocking per type..

(in another resolver..) 

  acl {
                allow type A      net 0.0.0.0/0
                allow type ANY    net 0.0.0.0/0
                allow type DNSKEY net 0.0.0.0/0
                allow type DS     net 0.0.0.0/0
                allow type HINFO  net 0.0.0.0/0
                allow type IXFR   net 0.0.0.0/0
                allow type MX     net 0.0.0.0/0
                allow type NS     net 0.0.0.0/0
                allow type SRV    net 0.0.0.0/0
                block
        }

Is there a away to allow and final action be to block? 

The Unknown: should be documented better.. 

upstreams:
- method:
    tls:
      no_sni: true
      name: dns.nextdns.io
      addr: 45.90.28.0:853
  tag: nextdns-28

- method:
    tls:
      no_sni: true
      name: dns.nextdns.io
      addr: 45.90.30.0:853
  tag: nextdns-30

- method:
    hybrid:
    - nextdns-28
    - nextdns-30
  tag: secure

**Comment by LEXUGE** [comment]
> Is there a way to block all qtypes, and then whitelist what you would want to work, instead of blocking per type..

Sure. Say you want to block all but `A` and `NS`.

```
if:
 qtype:
   - A
   - NS
then:
  # Do whatever here
else:
- blackhole
- end
```
