### ISSUE TITLE
发现一个问题，TTL的值不会随时间逝去而减少

### ISSUE THREAD

**Issue by fox85** [LEXUGE/dcompass#14]
配置文件内的：
cache_size: 4096

在首次发起请求获得回应后，接着经过了若干时间再对dcompass发起DNS请求，发现得到的应答内的TTL值不会随着时间的逝去而减少，TTL值始终保持不变。
请大佬帮忙看看，谢谢

版本是build-20210104_1021

**Comment by LEXUGE** [comment]
TTL 是指response能活多久，这个值是不会实时更新的
如果在超过TTL后请求一个已经cached的域名，那cache会返回，并且后台会发起请求尝试更新，保证响应速度

**Comment by fox85** [comment]
就是说，假如一个域名的IP已经发生变化，dcompass也是会根据实际发生的变化而给出正确的回应的，对吧？

**Comment by LEXUGE** [comment]
是的，cache策略是惰性更新，只有在被再次请求且超过TTL时才会发起更新。这个策略可以保证在网络环境很恶劣的情况下还能保持响应

**Comment by fox85** [comment]
> 是的，cache策略是惰性更新，只有在被再次请求且超过TTL时才会发起更新。这个策略可以保证在网络环境很恶劣的情况下还能保持响应

感谢大佬的答疑
