### ISSUE TITLE
[BUG] stability of CIDR with empty-line

### ISSUE THREAD

**Issue by honwen** [LEXUGE/dcompass#33]
```bash
echo  >> data/ipcn.txt   #add empty-line
dcompass -c success_cidr.yaml
```
```log
Using the config file specified: success_cidr.yaml
Error: An error encountered in the IP CIDR matcher.

Caused by:
    The CIDR string is incorrect.
```

**Comment by honwen** [comment]
example ipcn source:
- https://ispip.clang.cn/all_cn_cidr.txt
- https://github.com/17mon/china_ip_list/blob/master/china_ip_list.txt

**Comment by LEXUGE** [comment]
I think empty-line files are ambiguous. Are they meant to match all IPs or no IPs.
IP can list is part of the test suite, and it should be used free of error. Is there an unexpected behavior regarding that list?

**Comment by honwen** [comment]
> IP can list is part of the test suite, and it should be used free of error. Is there an unexpected behavior regarding that list?
bug-free

but [text-files-should-end-with-a-newline](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline/729795)

**Comment by LEXUGE** [comment]
Yes, there should be a newline terminator at the end of each file. However, as far as I am concerned, there IS a line terminator at the end of `./data/ipcn.txt`. This should be complying to the standard.

As for the file with `\n` only. I don't think this should be accepted as a valid input for IP CIDR matcher though.

**Comment by honwen** [comment]
> there IS a line terminator at the end of ./data/ipcn.txt

not so

![image](https://user-images.githubusercontent.com/12322033/107776390-77e80a00-6d7c-11eb-81fa-dbdf78ade305.png)

```bash
wc -l ipcn.txt
```
```
4729
```

refer:
> Case in point: wc -l filename.
> From the wc's manual we read:
> A line is defined as a string of characters delimited by a <newline> character.

**Comment by honwen** [comment]
TKs for Ur patient
