### ISSUE TITLE
建议添加缺省配置运行方案

### ISSUE THREAD

**Issue by ylx2016** [LEXUGE/dcompass#4]
比如没有指定配置文件名时，默认已当前目录下的config.yaml配置运行

**Comment by LEXUGE** [comment]
目前的行为是使用内置配置运行。内置配置是 `configs/default.yaml`.
可能可以双层 fallback, 手动指定 -> 当前目录 -> 内置配置
如果是 Windows 的话确实指定路径不太方便，可能需要有相应的服务管理程序

**Comment by ylx2016** [comment]
测试在windows相对路径当前目录下不指定配置文件configs/default.yaml都不会加载

**Comment by LEXUGE** [comment]
> 测试在windows相对路径当前目录下不指定配置文件configs/default.yaml都不会加载

能具体一些吗？是指直接退出？如果 `dcompass is ready!` 的话就是正常按照 `default.yaml` 运行了。

**Comment by LEXUGE** [comment]
https://github.com/LEXUGE/dcompass/commit/5673a29368a15aee0b763637e48a904d137de2e7

已经实现了双层 fallback, 可以下载最新的 build 来尝试一下，采用的是当前 *执行* 路径下的 `config.yaml`.

**Comment by ylx2016** [comment]
测试有效

**Comment by LEXUGE** [comment]
我刚刚增加了 IP CIDR 的支持，明天的自动构建版本会包括进这个功能，如果有需要可以更新

**Comment by ylx2016** [comment]
linux下有PID文件吗，我没找到，我想用monit守护，但是没找到PID在哪

**Comment by LEXUGE** [comment]
为什么不用 systemd 或者其他
systemd unit file 类似如下
```
[Unit]
After=network.target
Description=Dcompass DNS service

[Service]
AmbientCapabilities=CAP_NET_BIND_SERVICE
ExecStart=/path/to/dcompass
Restart=on-failure
User=dcompass
```

**Comment by LEXUGE** [comment]
如果有使用问题的话欢迎在 discussion page 讨论
https://github.com/LEXUGE/dcompass/discussions

close as the original issue was resolved.
