### ISSUE TITLE
请问是否有支持mips mipsel指令集的计划，以便在openwrt路由器上使用

### ISSUE THREAD

**Issue by nivrrex** [LEXUGE/dcompass#40]
因为有mips和mipsel结构的openwrt路由器，但是发现没有已经发布的mips版本，所以想自己编译尝试
但是编译时发现其中ring库不支持mips指令架构，无法解决，遂放弃
所以想问大大，后续是否有支持mips/mipsel等架构的计划？

**Comment by LEXUGE** [comment]
目前不支持的原因也正是 ring 的兼容性问题

**Comment by LEXUGE** [comment]
当然有计划，ring 一旦支持就会构建 mips 架构

**Comment by LEXUGE** [comment]
ref: https://github.com/briansmith/ring/pull/1181

**Comment by nivrrex** [comment]
OK~!
