### ISSUE TITLE
希望能支持freebsd

### ISSUE THREAD

**Issue by a1007152285** [LEXUGE/dcompass#49]
想在pfsense 搭建一个

**Comment by LEXUGE** [comment]
目前尚不清楚什么原因导致了freebsd的linking错误，正在排查

**Comment by LEXUGE** [comment]
已支持 `x86_64-unknown-freebsd`, `i686` 因为 ring 的原因不支持。

**Comment by LEXUGE** [comment]
请测试 https://github.com/LEXUGE/dcompass/releases/tag/build-20210403_2004
